### ISSUE TITLE
TİmeStamp

### ISSUE THREAD

**Issue by concu72** [ChenyXu/PancakeSwap-Arbitrage-Bot#2]
Hello, I tried the bot, it is getting successful results. But I think some corrections should be made regarding TimeStamp. I tried myself but couldn't. I think it would be better if it was arranged like this;
-When the bot starts, let it wait to get the current round lock time (the first round does not take action, it takes LockTimeStamp)
-Count the time in seconds to enter the next round pre-LockTimeStamp operation.
-When the waiting time requested by the user comes, it will calculate by taking the chain and dex price.
- As in the current settings, if the conditions are suitable, it should be processed within the specified n time or the relevant round does not operate.
It will be very nice if you edit it like this.

**Comment by ghost** [comment]
Thank you for your insight. I agree with you. I will try if I can improve this.
