### ISSUE TITLE
always no bet

### ISSUE THREAD

**Issue by gftyzz12** [ChenyXu/PancakeSwap-Arbitrage-Bot#3]
i have try to use this , but always no bet
PancakeSwap-Arbitrage-Bot$ python main.py 
History file Exists
145588 no bet
145589 no bet
145590 no bet

**Comment by ghost** [comment]
If the condition does not pass the filtering process, the bot will not bet. Sometimes it can take many rounds.

**Comment by gftyzz12** [comment]
ok thank you very much
